name: iOS PR CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2 # omit if .ruby-version file exists in project, or replace with your team’s supported ruby version
          bundler-cache: true
      - name: Bundle Install
        run: |
          cd iosApp
          bundle install
      - name: Setup secrets.json
        run: |
          echo '
            {
              "username": "${{ secrets.USERNAME }}"
              "password": "${{ secrets.PASSWORD }}"
            }
          ' >> iosApp/iosApp/Secrets/secrets.json
      - name: Setup apple_connect.json
        run: |
          echo '
            {
              "key_id": "${{ secrets.FASTLANE_KEY_ID }}",
              "issuer_id": "${{ secrets.FASTLANE_ISSUER_ID }}",
              "key": "${{ secrets.FASTLANE_AUTH_PRIVATE_KEY }}",
              "duration": 1200,
              "in_house": false
            }
          ' >> iosApp/fastlane/apple_connect.json
      - name: Install Firebase
        run: |
          curl -sL https://firebase.tools | bash
      - name: Login with Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run:
          firebase login --token ${{ secrets.FIREBASE_TOKEN }} --interactive
      - name: Update fastlane
        run: |
          bundle update fastlane
      - name: Build and upload to Firebase App Distribution
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER_IOS }}
          TEAM_NAME: ${{ secrets.TEAM_NAME_IOS }}
          FIREBASE_TESTER_GROUP: craftie-team
        run: |
          cd iosApp
          bundle exec fastlane do_everything_dev